set -g default-terminal "screen-256color"
set -g mouse on
set -g history-limit 100000

# 更快响应
set -sg escape-time 0

# true color
set -ga terminal-overrides ",*256col*:Tc"

# 编号从 1 开始
set -g base-index 1
setw -g pane-base-index 1
