
# TPM
set -g @plugin 'tmux-plugins/tpm'

# 推荐插件
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'sainnhe/tmux-fzf'
# 显示 prefix 状态
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
# 快速搜索（日志神器)
set -g @plugin 'tmux-plugins/tmux-copycat'
# 主题
set -g @plugin 'catppuccin/tmux'

# 自动保存
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
