#set -g status-bg colour234
#set -g status-fg colour137

#set -g status-left "#[fg=green]#S "
#set -g status-right "#[fg=yellow]%Y-%m-%d %H:%M"

#setw -g window-status-current-format "#[bg=green,fg=black] #I:#W "
#setw -g window-status-format "#[fg=white] #I:#W "

# 主题风格（推荐 mocha）
set -g @catppuccin_flavour 'mocha'

# 状态栏位置
set -g status-position bottom


# 样式
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator ""

# 左侧信息
set -g @catppuccin_status_left "session"

# 中间
set -g @catppuccin_status_modules_right "git cpu memory"

# 右侧信息
set -g @catppuccin_status_right "directory date_time"
